// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/mmlogic.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetrievePoolRequest struct {
	// The Pool representing the set of Filters to be queried.
	Pool                 *Pool    `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievePoolRequest) Reset()         { *m = RetrievePoolRequest{} }
func (m *RetrievePoolRequest) String() string { return proto.CompactTextString(m) }
func (*RetrievePoolRequest) ProtoMessage()    {}
func (*RetrievePoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa9c8aeaf311764, []int{0}
}

func (m *RetrievePoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievePoolRequest.Unmarshal(m, b)
}
func (m *RetrievePoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievePoolRequest.Marshal(b, m, deterministic)
}
func (m *RetrievePoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievePoolRequest.Merge(m, src)
}
func (m *RetrievePoolRequest) XXX_Size() int {
	return xxx_messageInfo_RetrievePoolRequest.Size(m)
}
func (m *RetrievePoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievePoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievePoolRequest proto.InternalMessageInfo

func (m *RetrievePoolRequest) GetPool() *Pool {
	if m != nil {
		return m.Pool
	}
	return nil
}

type RetrievePoolResponse struct {
	// The Tickets that meet the Filter criteria requested by the Pool.
	Ticket               []*Ticket `protobuf:"bytes,1,rep,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RetrievePoolResponse) Reset()         { *m = RetrievePoolResponse{} }
func (m *RetrievePoolResponse) String() string { return proto.CompactTextString(m) }
func (*RetrievePoolResponse) ProtoMessage()    {}
func (*RetrievePoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa9c8aeaf311764, []int{1}
}

func (m *RetrievePoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievePoolResponse.Unmarshal(m, b)
}
func (m *RetrievePoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievePoolResponse.Marshal(b, m, deterministic)
}
func (m *RetrievePoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievePoolResponse.Merge(m, src)
}
func (m *RetrievePoolResponse) XXX_Size() int {
	return xxx_messageInfo_RetrievePoolResponse.Size(m)
}
func (m *RetrievePoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievePoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievePoolResponse proto.InternalMessageInfo

func (m *RetrievePoolResponse) GetTicket() []*Ticket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func init() {
	proto.RegisterType((*RetrievePoolRequest)(nil), "api.RetrievePoolRequest")
	proto.RegisterType((*RetrievePoolResponse)(nil), "api.RetrievePoolResponse")
}

func init() { proto.RegisterFile("api/mmlogic.proto", fileDescriptor_caa9c8aeaf311764) }

var fileDescriptor_caa9c8aeaf311764 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x45, 0x89, 0x95, 0x8a, 0x19, 0x37, 0x8d, 0x5d, 0x8c, 0x83, 0xc5, 0x32, 0x6e, 0x8a, 0x8b,
	0x89, 0x8e, 0x82, 0xa0, 0xb8, 0x71, 0xad, 0x20, 0x83, 0xab, 0xee, 0xd2, 0xf2, 0x1c, 0x82, 0x99,
	0xbc, 0x38, 0x79, 0xd3, 0x8d, 0xb8, 0x11, 0x3f, 0x40, 0xf0, 0xd3, 0xfc, 0x05, 0x3f, 0x44, 0x92,
	0x56, 0x50, 0xec, 0x2a, 0x70, 0x0e, 0x37, 0xef, 0x72, 0xf9, 0x40, 0x39, 0x2d, 0x9b, 0xc6, 0x60,
	0xad, 0xe7, 0x85, 0x6b, 0x91, 0x50, 0xf4, 0x94, 0xd3, 0x99, 0x88, 0x1c, 0xbc, 0x57, 0x35, 0xf8,
	0xa5, 0xc8, 0xf6, 0x6b, 0xc4, 0xda, 0x80, 0x0c, 0x4a, 0x59, 0x8b, 0xa4, 0x48, 0xa3, 0x5d, 0xd9,
	0xfc, 0x8c, 0xef, 0x56, 0x40, 0xad, 0x86, 0x05, 0xdc, 0x21, 0x9a, 0x0a, 0x9e, 0x3a, 0xf0, 0x24,
	0x46, 0x7c, 0xd3, 0x21, 0x9a, 0x94, 0x8d, 0xd9, 0x24, 0x29, 0xb7, 0x0b, 0xe5, 0x74, 0x11, 0x7d,
	0xc4, 0xf9, 0x25, 0x1f, 0xfe, 0x4d, 0x79, 0x87, 0xd6, 0x83, 0x38, 0xe4, 0x7d, 0xd2, 0xf3, 0x47,
	0xa0, 0x94, 0x8d, 0x7b, 0x93, 0xa4, 0x4c, 0x62, 0xf0, 0x3e, 0xa2, 0x6a, 0xa5, 0xca, 0x77, 0xc6,
	0xb7, 0x6e, 0x9b, 0x9b, 0xd0, 0x5d, 0xbc, 0x31, 0xbe, 0xf3, 0xfb, 0x27, 0x91, 0xc6, 0xc4, 0x9a,
	0x4a, 0xd9, 0xde, 0x1a, 0xb3, 0x3c, 0x9b, 0x5f, 0xbd, 0x7e, 0x7e, 0x7d, 0x6c, 0x9c, 0xe7, 0x03,
	0xb9, 0x38, 0xf9, 0x99, 0x45, 0x86, 0xa2, 0xfe, 0x82, 0x1d, 0x4d, 0x0f, 0xc4, 0xe8, 0x1f, 0x97,
	0xcf, 0xe1, 0x29, 0xac, 0x6a, 0xe0, 0xe5, 0x98, 0x5d, 0x0f, 0xa7, 0x42, 0x5b, 0x82, 0xd6, 0x2a,
	0x23, 0x1f, 0x3a, 0xea, 0x5a, 0x90, 0x6e, 0x36, 0xeb, 0xc7, 0x89, 0x4e, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xbc, 0xa3, 0x78, 0x2d, 0x6e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MmLogicClient is the client API for MmLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MmLogicClient interface {
	// RetrievePool gets the list of Tickets that match every Filter in the
	// specified Pool.
	// TODO: Consider renaming to "GetPool" to be consistent with HTTP REST CRUD
	// conventions. Right now there's a GET and a POST for this verb.
	RetrievePool(ctx context.Context, in *RetrievePoolRequest, opts ...grpc.CallOption) (MmLogic_RetrievePoolClient, error)
}

type mmLogicClient struct {
	cc *grpc.ClientConn
}

func NewMmLogicClient(cc *grpc.ClientConn) MmLogicClient {
	return &mmLogicClient{cc}
}

func (c *mmLogicClient) RetrievePool(ctx context.Context, in *RetrievePoolRequest, opts ...grpc.CallOption) (MmLogic_RetrievePoolClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MmLogic_serviceDesc.Streams[0], "/api.MmLogic/RetrievePool", opts...)
	if err != nil {
		return nil, err
	}
	x := &mmLogicRetrievePoolClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MmLogic_RetrievePoolClient interface {
	Recv() (*RetrievePoolResponse, error)
	grpc.ClientStream
}

type mmLogicRetrievePoolClient struct {
	grpc.ClientStream
}

func (x *mmLogicRetrievePoolClient) Recv() (*RetrievePoolResponse, error) {
	m := new(RetrievePoolResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MmLogicServer is the server API for MmLogic service.
type MmLogicServer interface {
	// RetrievePool gets the list of Tickets that match every Filter in the
	// specified Pool.
	// TODO: Consider renaming to "GetPool" to be consistent with HTTP REST CRUD
	// conventions. Right now there's a GET and a POST for this verb.
	RetrievePool(*RetrievePoolRequest, MmLogic_RetrievePoolServer) error
}

func RegisterMmLogicServer(s *grpc.Server, srv MmLogicServer) {
	s.RegisterService(&_MmLogic_serviceDesc, srv)
}

func _MmLogic_RetrievePool_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RetrievePoolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MmLogicServer).RetrievePool(m, &mmLogicRetrievePoolServer{stream})
}

type MmLogic_RetrievePoolServer interface {
	Send(*RetrievePoolResponse) error
	grpc.ServerStream
}

type mmLogicRetrievePoolServer struct {
	grpc.ServerStream
}

func (x *mmLogicRetrievePoolServer) Send(m *RetrievePoolResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MmLogic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MmLogic",
	HandlerType: (*MmLogicServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RetrievePool",
			Handler:       _MmLogic_RetrievePool_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/mmlogic.proto",
}
