# Golang application builder steps
FROM python:3.5.3 as builder
WORKDIR /usr/src/open-match
COPY examples/functions/python3/simple examples/functions/python3/simple
COPY config config
WORKDIR /usr/src/open-match/examples/functions/python3/simple
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "./mmf.py"]
