<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/protobuf-spec/messages.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PlayerPools are defined by a set of 'hard' filters, and can be filled in
 * with the players that match those filters.
 * PlayerPools contain a number of fields, but many gRPC calls that take a
 * PlayerPool as input only require a few of them to be filled in.  Check the
 * gRPC function in question for more details.
 *
 * Generated from protobuf message <code>messages.PlayerPool</code>
 */
class PlayerPool extends \Google\Protobuf\Internal\Message
{
    /**
     * Arbitrary developer-chosen, human-readable string.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Filters are logical AND-ed (a player must match every filter).
     *
     * Generated from protobuf field <code>repeated .messages.Filter filters = 2;</code>
     */
    private $filters;
    /**
     * Roster of players that match all filters.
     *
     * Generated from protobuf field <code>.messages.Roster roster = 3;</code>
     */
    private $roster = null;
    /**
     * Statisticss for the last time this Pool was retrieved from state storage. 
     *
     * Generated from protobuf field <code>.messages.Stats stats = 4;</code>
     */
    private $stats = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Arbitrary developer-chosen, human-readable string.
     *     @type \Messages\Filter[]|\Google\Protobuf\Internal\RepeatedField $filters
     *           Filters are logical AND-ed (a player must match every filter).
     *     @type \Messages\Roster $roster
     *           Roster of players that match all filters.
     *     @type \Messages\Stats $stats
     *           Statisticss for the last time this Pool was retrieved from state storage. 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\ProtobufSpec\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Arbitrary developer-chosen, human-readable string.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Arbitrary developer-chosen, human-readable string.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Filters are logical AND-ed (a player must match every filter).
     *
     * Generated from protobuf field <code>repeated .messages.Filter filters = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * Filters are logical AND-ed (a player must match every filter).
     *
     * Generated from protobuf field <code>repeated .messages.Filter filters = 2;</code>
     * @param \Messages\Filter[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFilters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Filter::class);
        $this->filters = $arr;

        return $this;
    }

    /**
     * Roster of players that match all filters.
     *
     * Generated from protobuf field <code>.messages.Roster roster = 3;</code>
     * @return \Messages\Roster
     */
    public function getRoster()
    {
        return $this->roster;
    }

    /**
     * Roster of players that match all filters.
     *
     * Generated from protobuf field <code>.messages.Roster roster = 3;</code>
     * @param \Messages\Roster $var
     * @return $this
     */
    public function setRoster($var)
    {
        GPBUtil::checkMessage($var, \Messages\Roster::class);
        $this->roster = $var;

        return $this;
    }

    /**
     * Statisticss for the last time this Pool was retrieved from state storage. 
     *
     * Generated from protobuf field <code>.messages.Stats stats = 4;</code>
     * @return \Messages\Stats
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Statisticss for the last time this Pool was retrieved from state storage. 
     *
     * Generated from protobuf field <code>.messages.Stats stats = 4;</code>
     * @param \Messages\Stats $var
     * @return $this
     */
    public function setStats($var)
    {
        GPBUtil::checkMessage($var, \Messages\Stats::class);
        $this->stats = $var;

        return $this;
    }

}

