// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.0
// source: internal/api/messages.proto

package ipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb "open-match.dev/open-match/pkg/pb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackfillInternal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents a backfill entity which is used to fill partially full matches
	Backfill *pb.Backfill `protobuf:"bytes,1,opt,name=backfill,proto3" json:"backfill,omitempty"`
	// List of ticket IDs associated with a current backfill
	TicketIds     []string `protobuf:"bytes,2,rep,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillInternal) Reset() {
	*x = BackfillInternal{}
	mi := &file_internal_api_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillInternal) ProtoMessage() {}

func (x *BackfillInternal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillInternal.ProtoReflect.Descriptor instead.
func (*BackfillInternal) Descriptor() ([]byte, []int) {
	return file_internal_api_messages_proto_rawDescGZIP(), []int{0}
}

func (x *BackfillInternal) GetBackfill() *pb.Backfill {
	if x != nil {
		return x.Backfill
	}
	return nil
}

func (x *BackfillInternal) GetTicketIds() []string {
	if x != nil {
		return x.TicketIds
	}
	return nil
}

var File_internal_api_messages_proto protoreflect.FileDescriptor

const file_internal_api_messages_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/api/messages.proto\x12\x12openmatch.internal\x1a\x12api/messages.proto\"b\n" +
	"\x10BackfillInternal\x12/\n" +
	"\bbackfill\x18\x01 \x01(\v2\x13.openmatch.BackfillR\bbackfill\x12\x1d\n" +
	"\n" +
	"ticket_ids\x18\x02 \x03(\tR\tticketIdsB(Z&open-match.dev/open-match/internal/ipbb\x06proto3"

var (
	file_internal_api_messages_proto_rawDescOnce sync.Once
	file_internal_api_messages_proto_rawDescData []byte
)

func file_internal_api_messages_proto_rawDescGZIP() []byte {
	file_internal_api_messages_proto_rawDescOnce.Do(func() {
		file_internal_api_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_messages_proto_rawDesc), len(file_internal_api_messages_proto_rawDesc)))
	})
	return file_internal_api_messages_proto_rawDescData
}

var file_internal_api_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_api_messages_proto_goTypes = []any{
	(*BackfillInternal)(nil), // 0: openmatch.internal.BackfillInternal
	(*pb.Backfill)(nil),      // 1: openmatch.Backfill
}
var file_internal_api_messages_proto_depIdxs = []int32{
	1, // 0: openmatch.internal.BackfillInternal.backfill:type_name -> openmatch.Backfill
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_messages_proto_init() }
func file_internal_api_messages_proto_init() {
	if File_internal_api_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_messages_proto_rawDesc), len(file_internal_api_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_messages_proto_goTypes,
		DependencyIndexes: file_internal_api_messages_proto_depIdxs,
		MessageInfos:      file_internal_api_messages_proto_msgTypes,
	}.Build()
	File_internal_api_messages_proto = out.File
	file_internal_api_messages_proto_goTypes = nil
	file_internal_api_messages_proto_depIdxs = nil
}
