{
 "title": "gRPC",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "timewindow", "label": "Time Window", "query": "5m,10m,15m,30m,1h,4h" }
  ]
 },
 "panels": [
  { "title": "gRPC Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_client_method)(rate(grpc_io_client_completed_rpcs[$timewindow]))",
     "legendFormat": "{{grpc_client_method}}"
    }
   ]
  },
  {
   "title": "Server Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_server_method)(rate(grpc_io_server_completed_rpcs[$timewindow]))",
     "legendFormat": "Method: {{grpc_server_method}} "
    }
   ]
  },
  {
   "title": "gRPC Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (\n  label_replace(\n    sum by (grpc_server_method) (rate(grpc_io_server_completed_rpcs{grpc_server_status!=\"OK\"}[$timewindow])), \n    \"method\", \n    \"$1\", \n    \"grpc_server_method\", \n    \"(.*)\"\n  )\nor\n  label_replace(\n    sum by (grpc_client_method) (rate(grpc_io_client_completed_rpcs{grpc_client_status!=\"OK\"}[$timewindow])), \n    \"method\", \n    \"$1\", \n    \"grpc_client_method\", \n    \"(.*)\"\n  )\n)\n/\nsum by (method) (\n  label_replace(\n    sum by (grpc_server_method) (rate(grpc_io_server_completed_rpcs[$timewindow])), \n    \"method\", \n    \"$1\", \n    \"grpc_server_method\", \n    \"(.*)\"\n  )\nor\n  label_replace(\n    sum by (grpc_client_method) (rate(grpc_io_client_completed_rpcs[$timewindow])), \n    \"method\", \n    \"$1\", \n    \"grpc_client_method\", \n    \"(.*)\"\n  )\n) * 100\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Network IO per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum by (method) (\n    label_replace(\n      rate(grpc_io_server_received_bytes_per_rpc_sum[$timewindow]), \n      \"method\", \n      \"$1\", \n      \"grpc_server_method\", \n      \"(.*)\"\n    )\n  or\n    label_replace(\n      rate(grpc_io_client_sent_bytes_per_rpc_sum[$timewindow]), \n      \"method\", \n      \"$1\", \n      \"grpc_client_method\", \n      \"(.*)\"\n    )\n  )\n  \n  /\n  \n  sum by (method) (\n    label_replace(\n      rate(grpc_io_server_received_bytes_per_rpc_count[$timewindow]), \n      \"method\", \n      \"$1\", \n      \"grpc_server_method\", \n      \"(.*)\"\n    )\n  or\n    label_replace(\n      rate(grpc_io_client_sent_bytes_per_rpc_count[$timewindow]), \n      \"method\", \n      \"$1\", \n      \"grpc_client_method\", \n      \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "Input Per Second"
    },
    {
     "expr": "sum(\n  sum by (method) (\n    label_replace(\n      rate(grpc_io_server_sent_bytes_per_rpc_sum[$timewindow]), \n      \"method\", \n      \"$1\", \n      \"grpc_server_method\", \n      \"(.*)\"\n    )\n  or\n    label_replace(\n      rate(grpc_io_client_received_bytes_per_rpc_sum[$timewindow]), \n      \"method\", \n      \"$1\", \n      \"grpc_client_method\", \n      \"(.*)\"\n    )\n  )\n  \n  /\n  \n  sum by (method) (\n    label_replace(\n      rate(grpc_io_server_sent_bytes_per_rpc_count[$timewindow]), \n      \"method\", \n      \"$1\", \n      \"grpc_server_method\", \n      \"(.*)\"\n    )\n  or\n    label_replace(\n      rate(grpc_io_client_received_bytes_per_rpc_count[$timewindow]), \n      \"method\", \n      \"$1\", \n      \"grpc_client_method\", \n      \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "Output Per Second"
    }
   ]
  },
  { "title": "openmatch.Mmlogic/QueryTickets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Bytes Sent per Call: openmatch.MmLogic/QueryTickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_server_received_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_received_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_received_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_server_received_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_server_received_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_server_received_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Bytes Received per Call: openmatch.MmLogic/QueryTickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_server_sent_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_sent_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_sent_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_server_sent_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_server_sent_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_server_sent_bytes_per_rpc_bucket{grpc_server_method=\"openmatch.MmLogic/QueryTickets\"}[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Client RTT: openmatch.Backend/AssignTickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile Latency"
    }
   ]
  },
  {
   "title": "openmatch.Backend/AssignTickets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Bytes Sent per Call: openmatch.Backend/AssignTickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Bytes Received per Call: openmatch.Backend/AssignTickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Client RTT: openmatch.Backend/AssignTickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/AssignTickets\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile Latency"
    }
   ]
  },
  {
   "title": "openmatch.Frontend/CreateTicket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Bytes Sent per Call: openmatch.Frontend/CreateTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Bytes Received per Call: openmatch.Frontend/CreateTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Client RTT: openmatch.Frontend/CreateTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/CreateTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile Latency"
    }
   ]
  },
  { "title": "openmatch.Evaluator/Evaluate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Bytes Sent per Call: openmatch.Evaluator/Evaluate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Bytes Received per Call: openmatch.Evaluator/Evaluate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Client RTT: openmatch.Evaluator/Evaluate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Evaluator/Evaluate\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile Latency"
    }
   ]
  },
  { "title": "openmatch.MatchFunction/Run", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Bytes Sent per Call: openmatch.MatchFunction/Run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Bytes Received per Call: openmatch.MatchFunction/Run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Client RTT: openmatch.MatchFunction/Run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.MatchFunction/Run\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile Latency"
    }
   ]
  },
  {
   "title": "openmatch.Frontend/FetchMatches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 }
  },
  {
   "title": "Bytes Sent per Call: openmatch.Backend/FetchMatches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Bytes Received per Call: openmatch.Backend/FetchMatches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Client RTT: openmatch.Backend/FetchMatches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Backend/FetchMatches\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile Latency"
    }
   ]
  },
  {
   "title": "openmatch.Synchronizer/Synchronize",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 }
  },
  {
   "title": "Bytes Sent per Call: openmatch.internal.Synchronizer/Synchronize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Bytes Received per Call: openmatch.internal.Synchronizer/Synchronize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Client RTT: openmatch.internal.Synchronizer/Synchronize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.internal.Synchronizer/Synchronize\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile Latency"
    }
   ]
  },
  {
   "title": "openmatch.Frontend/DeleteTicket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 }
  },
  {
   "title": "Bytes Sent per Call: openmatch.Frontend/DeleteTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_sent_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Bytes Received per Call: openmatch.Frontend/DeleteTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_received_bytes_per_rpc_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Client RTT: openmatch.Frontend/DeleteTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99.9%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "99%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "95%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "90%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "50%-ile Latency"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"openmatch.Frontend/DeleteTicket\"}[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "10%-ile Latency"
    }
   ]
  }
 ]
}