{
 "title": "Match Making",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Ticket Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Backfill Tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "open_match_dev_query_total_backfill_tickets",
     "legendFormat": "Total: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total Active Tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "open_match_dev_query_total_active_tickets",
     "legendFormat": "Total: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total Pending Tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "open_match_dev_query_total_pending_tickets",
     "legendFormat": "Total: {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Bytes per Ticket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_frontend_total_bytes_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_frontend_total_bytes_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_frontend_total_bytes_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_frontend_total_bytes_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_frontend_total_bytes_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_frontend_total_bytes_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "SearchFields per Ticket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_frontend_searchfields_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_frontend_searchfields_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_frontend_searchfields_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_frontend_searchfields_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_frontend_searchfields_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_frontend_searchfields_per_ticket_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ticket Assigned/Release Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(open_match_dev_backend_tickets_assigned[5m]))",
     "legendFormat": "assigned"
    },
    {
     "expr": "sum(rate(open_match_dev_backend_tickets_released[5m]))",
     "legendFormat": "released"
    }
   ]
  },
  {
   "title": "Tickets per Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_backend_tickets_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_backend_tickets_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_backend_tickets_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_backend_tickets_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_backend_tickets_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_backend_tickets_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Total Bytes per Match",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_backend_total_bytes_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_backend_total_bytes_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_backend_total_bytes_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_backend_total_bytes_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_backend_total_bytes_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_backend_total_bytes_per_match_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Query Cache Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "open_match_dev_query_total_cached_items",
     "legendFormat": "Total: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Query Cache Fetch Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(open_match_dev_query_total_fetched_items[5m])",
     "legendFormat": "Total: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Tickets per Query",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Query Cache Waiting Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Query Cache Update Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Query Cache Update Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(open_match_dev_query_cache_updates[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Evaluator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Matches per Evaluate Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_evaluator_matches_per_request_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_evaluator_matches_per_request_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_evaluator_matches_per_request_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_evaluator_matches_per_request_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_evaluator_matches_per_request_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_evaluator_matches_per_request_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Matches per Evaluate Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_evaluator_matches_per_response_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_evaluator_matches_per_response_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_evaluator_matches_per_response_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_evaluator_matches_per_response_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_evaluator_matches_per_response_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_evaluator_matches_per_response_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Collided Matches per Evaluate",
   "type": "graph",
   "description": "Only applies when using the default evaluator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(open_match_dev_defaulteval_collided_matches_per_call[5m]))\n",
     "legendFormat": "99.9%-ile"
    }
   ]
  },
  { "title": "Synchronizer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Synchronizer Registration MMF Done Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Synchronizer Registration Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Synchronizer Iteration Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(open_match_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(open_match_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(open_match_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(open_match_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(open_match_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(open_match_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  }
 ]
}