{
 "title": "Storage asd",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "timewindow", "label": "Time Window", "query": "5m,10m,15m,30m,1h,4h" }
  ]
 },
 "panels": [
  {
   "title": "Write Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(statestore_createticketcount[$timewindow]))",
     "legendFormat": "Create Ticket"
    },
    {
     "expr": "sum(rate(statestore_deleteticketcount[$timewindow]))",
     "legendFormat": "Delete Ticket Count"
    },
    {
     "expr": "sum(rate(statestore_indexticketcount[$timewindow]))",
     "legendFormat": "Index Ticket Count"
    },
    {
     "expr": "sum(rate(statestore_deindexticketcount[$timewindow]))",
     "legendFormat": "Deindex Ticket Count"
    },
    {
     "expr": "sum(rate(statestore_addticketstoignorelistcount[$timewindow]))",
     "legendFormat": "IgnoreList Add Count"
    },
    {
     "expr": "sum(rate(statestore_deleteticketfromignorelistcount[$timewindow]))",
     "legendFormat": "IgnoreList Delete Count"
    },
    {
     "expr": "sum(rate(statestore_updateassignmentcount[$timewindow]))",
     "legendFormat": "Update Assignment Count"
    }
   ]
  },
  {
   "title": "Read Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(statestore_getassignmentscount[$timewindow]))",
     "legendFormat": "Get Assignment Count"
    },
    {
     "expr": "sum(rate(statestore_filterticketcount[$timewindow]))",
     "legendFormat": "Filter Ticket Count"
    },
    {
     "expr": "sum(rate(statestore_getticketcount[$timewindow]))",
     "legendFormat": "Get Ticket Count"
    }
   ]
  },
  {
   "title": "Time Elapsed: CreateTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: DeleteTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: GetTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: GetAssignments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: IndexTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: DeindexTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: FilterTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: UpdateAssignment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: AddTicketsToIgnoreList",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: DeleteTicketFromIgnoreList",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  }
 ]
}