{
 "title": "Synchronizer Time Window",
 "time": { "from": "2019-11-25T23:17:33.056Z", "to": "2019-11-25T23:26:03.409Z" },
 "panels": [
  {
   "title": "Proposal Collection Time",
   "type": "graph",
   "description": "Time distribution to send and receive a response from the MMFs in a backend service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(backend_proposal_collection_bucket[5m])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(backend_proposal_collection_bucket[5m])) by (le))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(backend_proposal_collection_bucket[5m])) by (le))",
     "legendFormat": "75 percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(backend_proposal_collection_bucket[5m])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(backend_proposal_collection_bucket[5m])) by (le))",
     "legendFormat": "10 percentile"
    }
   ]
  },
  {
   "title": "Register Time",
   "type": "graph",
   "description": "Time distribution to send and receive a response from `synchronizer.Register` call in a backend service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(backend_register_bucket[5m])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(backend_register_bucket[5m])) by (le))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(backend_register_bucket[5m])) by (le))",
     "legendFormat": "75 percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(backend_register_bucket[5m])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(backend_register_bucket[5m])) by (le))",
     "legendFormat": "10 percentile"
    }
   ]
  },
  {
   "title": "Evaluate Proposals Time",
   "type": "graph",
   "description": "Time distribution to send and receive a response from synchronizer.evaluate call in a backend service",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(backend_evaluate_proposals_bucket[5m])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(backend_evaluate_proposals_bucket[5m])) by (le))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(backend_evaluate_proposals_bucket[5m])) by (le))",
     "legendFormat": "75 percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(backend_evaluate_proposals_bucket[5m])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(backend_evaluate_proposals_bucket[5m])) by (le))",
     "legendFormat": "10 percentile"
    }
   ]
  }
 ]
}