{
 "title": "gRPC",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "timewindow", "label": "Time Window", "query": "5m,10m,15m,30m,1h,4h" }
  ]
 },
 "panels": [
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_io_client_received_messages_per_rpc_count[$timewindow])",
     "legendFormat": "{{component}} {{grpc_client_method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(grpc_io_client_roundtrip_latency_bucket[$timewindow]))",
     "legendFormat": "{{component}} {{grpc_client_method}}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_io_server_received_messages_per_rpc_count[$timewindow])",
     "legendFormat": "Recv /{{component}}.{{grpc_server_method}}"
    },
    {
     "expr": "rate(grpc_io_server_sent_messages_per_rpc_count[$timewindow])",
     "legendFormat": "Sent /{{component}}.{{grpc_server_method}}"
    }
   ]
  },
  {
   "title": "RPC Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(grpc_io_server_server_latency_bucket[$timewindow]))",
     "legendFormat": "{{grpc_server_method}}"
    }
   ]
  }
 ]
}