// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/backend.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FunctionConfig_Type int32

const (
	FunctionConfig_GRPC FunctionConfig_Type = 0
	FunctionConfig_REST FunctionConfig_Type = 1
)

var FunctionConfig_Type_name = map[int32]string{
	0: "GRPC",
	1: "REST",
}

var FunctionConfig_Type_value = map[string]int32{
	"GRPC": 0,
	"REST": 1,
}

func (x FunctionConfig_Type) String() string {
	return proto.EnumName(FunctionConfig_Type_name, int32(x))
}

func (FunctionConfig_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8dab762378f455cd, []int{0, 0}
}

// Configuration for the Match Function to be triggered by Open Match to
// generate proposals.
type FunctionConfig struct {
	Host                 string              `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32               `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type                 FunctionConfig_Type `protobuf:"varint,3,opt,name=type,proto3,enum=api.FunctionConfig_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FunctionConfig) Reset()         { *m = FunctionConfig{} }
func (m *FunctionConfig) String() string { return proto.CompactTextString(m) }
func (*FunctionConfig) ProtoMessage()    {}
func (*FunctionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dab762378f455cd, []int{0}
}

func (m *FunctionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionConfig.Unmarshal(m, b)
}
func (m *FunctionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionConfig.Marshal(b, m, deterministic)
}
func (m *FunctionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionConfig.Merge(m, src)
}
func (m *FunctionConfig) XXX_Size() int {
	return xxx_messageInfo_FunctionConfig.Size(m)
}
func (m *FunctionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionConfig proto.InternalMessageInfo

func (m *FunctionConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *FunctionConfig) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *FunctionConfig) GetType() FunctionConfig_Type {
	if m != nil {
		return m.Type
	}
	return FunctionConfig_GRPC
}

type FetchMatchesRequest struct {
	// Configuration of the MatchFunction to be executed for the given list of MatchProfiles
	Config *FunctionConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// MatchProfiles for which this MatchFunction should be executed.
	Profiles             []*MatchProfile `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FetchMatchesRequest) Reset()         { *m = FetchMatchesRequest{} }
func (m *FetchMatchesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchMatchesRequest) ProtoMessage()    {}
func (*FetchMatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dab762378f455cd, []int{1}
}

func (m *FetchMatchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchMatchesRequest.Unmarshal(m, b)
}
func (m *FetchMatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchMatchesRequest.Marshal(b, m, deterministic)
}
func (m *FetchMatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchMatchesRequest.Merge(m, src)
}
func (m *FetchMatchesRequest) XXX_Size() int {
	return xxx_messageInfo_FetchMatchesRequest.Size(m)
}
func (m *FetchMatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchMatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchMatchesRequest proto.InternalMessageInfo

func (m *FetchMatchesRequest) GetConfig() *FunctionConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *FetchMatchesRequest) GetProfiles() []*MatchProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type FetchMatchesResponse struct {
	// Result Match for the requested MatchProfile.
	// Note that OpenMatch will validate the proposals, a valid match should contain at least one ticket.
	Match                *Match   `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchMatchesResponse) Reset()         { *m = FetchMatchesResponse{} }
func (m *FetchMatchesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchMatchesResponse) ProtoMessage()    {}
func (*FetchMatchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dab762378f455cd, []int{2}
}

func (m *FetchMatchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchMatchesResponse.Unmarshal(m, b)
}
func (m *FetchMatchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchMatchesResponse.Marshal(b, m, deterministic)
}
func (m *FetchMatchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchMatchesResponse.Merge(m, src)
}
func (m *FetchMatchesResponse) XXX_Size() int {
	return xxx_messageInfo_FetchMatchesResponse.Size(m)
}
func (m *FetchMatchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchMatchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchMatchesResponse proto.InternalMessageInfo

func (m *FetchMatchesResponse) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

type AssignTicketsRequest struct {
	// List of Ticket IDs for which the Assignment is to be made.
	TicketIds []string `protobuf:"bytes,1,rep,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`
	// Assignment to be associated with the Ticket IDs.
	Assignment           *Assignment `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AssignTicketsRequest) Reset()         { *m = AssignTicketsRequest{} }
func (m *AssignTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*AssignTicketsRequest) ProtoMessage()    {}
func (*AssignTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dab762378f455cd, []int{3}
}

func (m *AssignTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignTicketsRequest.Unmarshal(m, b)
}
func (m *AssignTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignTicketsRequest.Marshal(b, m, deterministic)
}
func (m *AssignTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignTicketsRequest.Merge(m, src)
}
func (m *AssignTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_AssignTicketsRequest.Size(m)
}
func (m *AssignTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignTicketsRequest proto.InternalMessageInfo

func (m *AssignTicketsRequest) GetTicketIds() []string {
	if m != nil {
		return m.TicketIds
	}
	return nil
}

func (m *AssignTicketsRequest) GetAssignment() *Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

type AssignTicketsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignTicketsResponse) Reset()         { *m = AssignTicketsResponse{} }
func (m *AssignTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*AssignTicketsResponse) ProtoMessage()    {}
func (*AssignTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dab762378f455cd, []int{4}
}

func (m *AssignTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignTicketsResponse.Unmarshal(m, b)
}
func (m *AssignTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignTicketsResponse.Marshal(b, m, deterministic)
}
func (m *AssignTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignTicketsResponse.Merge(m, src)
}
func (m *AssignTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_AssignTicketsResponse.Size(m)
}
func (m *AssignTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignTicketsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("api.FunctionConfig_Type", FunctionConfig_Type_name, FunctionConfig_Type_value)
	proto.RegisterType((*FunctionConfig)(nil), "api.FunctionConfig")
	proto.RegisterType((*FetchMatchesRequest)(nil), "api.FetchMatchesRequest")
	proto.RegisterType((*FetchMatchesResponse)(nil), "api.FetchMatchesResponse")
	proto.RegisterType((*AssignTicketsRequest)(nil), "api.AssignTicketsRequest")
	proto.RegisterType((*AssignTicketsResponse)(nil), "api.AssignTicketsResponse")
}

func init() { proto.RegisterFile("api/backend.proto", fileDescriptor_8dab762378f455cd) }

var fileDescriptor_8dab762378f455cd = []byte{
	// 688 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x4d, 0x53, 0xdb, 0x38,
	0x18, 0x5e, 0x3b, 0xe1, 0x23, 0x62, 0x97, 0x05, 0xc1, 0xee, 0x06, 0xcf, 0x7e, 0x68, 0xbd, 0xdb,
	0x99, 0x4c, 0x4a, 0xac, 0xe0, 0x72, 0xe8, 0xa4, 0xd3, 0x19, 0x02, 0x85, 0x0e, 0x33, 0xb4, 0x65,
	0x0c, 0xd3, 0x43, 0x2f, 0x1d, 0xc7, 0x7e, 0x63, 0xbb, 0x89, 0x25, 0x61, 0xc9, 0x50, 0xae, 0x1c,
	0x7b, 0x6c, 0x6f, 0xfd, 0x09, 0xbd, 0xf5, 0xb7, 0xf4, 0xd2, 0x1f, 0xd0, 0xfe, 0x8f, 0x8e, 0xe5,
	0x40, 0x12, 0xc8, 0x29, 0xf2, 0xf3, 0x3c, 0x7a, 0x9e, 0xf7, 0x7d, 0x25, 0x05, 0xad, 0xfa, 0x22,
	0xa1, 0x3d, 0x3f, 0x18, 0x00, 0x0b, 0x1d, 0x91, 0x71, 0xc5, 0x71, 0xc5, 0x17, 0x89, 0x85, 0x0b,
	0x3c, 0x05, 0x29, 0xfd, 0x08, 0x64, 0x49, 0x58, 0x7f, 0x46, 0x9c, 0x47, 0x43, 0xa0, 0x05, 0xe5,
	0x33, 0xc6, 0x95, 0xaf, 0x12, 0xce, 0xae, 0xd9, 0x4d, 0xfd, 0x13, 0xb4, 0x22, 0x60, 0x2d, 0x79,
	0xe1, 0x47, 0x11, 0x64, 0x94, 0x0b, 0xad, 0xb8, 0xab, 0xb6, 0xaf, 0x0c, 0xb4, 0x7c, 0x90, 0xb3,
	0xa0, 0xc0, 0xf6, 0x38, 0xeb, 0x27, 0x11, 0xc6, 0xa8, 0x1a, 0x73, 0xa9, 0xea, 0x06, 0x31, 0x1a,
	0x35, 0x4f, 0xaf, 0x0b, 0x4c, 0xf0, 0x4c, 0xd5, 0x4d, 0x62, 0x34, 0xe6, 0x3c, 0xbd, 0xc6, 0x9b,
	0xa8, 0xaa, 0x2e, 0x05, 0xd4, 0x2b, 0xc4, 0x68, 0x2c, 0xbb, 0x75, 0xc7, 0x17, 0x89, 0x33, 0x6d,
	0xe5, 0x9c, 0x5e, 0x0a, 0xf0, 0xb4, 0xca, 0xb6, 0x50, 0xb5, 0xf8, 0xc2, 0x8b, 0xa8, 0xfa, 0xd4,
	0x3b, 0xde, 0x5b, 0xf9, 0xa9, 0x58, 0x79, 0xfb, 0x27, 0xa7, 0x2b, 0x86, 0x7d, 0x86, 0xd6, 0x0e,
	0x40, 0x05, 0xf1, 0x33, 0x5f, 0x05, 0x31, 0x48, 0x0f, 0xce, 0x72, 0x90, 0x0a, 0xdf, 0x47, 0xf3,
	0x81, 0xf6, 0xd1, 0xa5, 0x2c, 0xb9, 0x6b, 0x33, 0x22, 0xbc, 0x91, 0x04, 0xb7, 0xd0, 0xa2, 0xc8,
	0x78, 0x3f, 0x19, 0x82, 0xac, 0x9b, 0xa4, 0xd2, 0x58, 0x72, 0x57, 0xb5, 0x5c, 0x7b, 0x1e, 0x97,
	0x8c, 0x77, 0x23, 0xb1, 0x1f, 0xa2, 0xf5, 0xe9, 0x48, 0x29, 0x38, 0x93, 0x80, 0x09, 0x9a, 0x4b,
	0x0b, 0x68, 0x14, 0x89, 0xc6, 0x1e, 0x5e, 0x49, 0xd8, 0x7d, 0xb4, 0xde, 0x95, 0x32, 0x89, 0xd8,
	0x69, 0x12, 0x0c, 0x40, 0xdd, 0x54, 0xfb, 0x17, 0x42, 0x4a, 0x23, 0xaf, 0x93, 0x50, 0xd6, 0x0d,
	0x52, 0x69, 0xd4, 0xbc, 0x5a, 0x89, 0x1c, 0x86, 0x12, 0x53, 0x84, 0x7c, 0xbd, 0x2d, 0x05, 0x56,
	0xce, 0x71, 0xc9, 0xfd, 0x55, 0xbb, 0x77, 0x6f, 0x60, 0x6f, 0x42, 0x62, 0xff, 0x81, 0x7e, 0xbb,
	0x95, 0x53, 0x96, 0xe8, 0x7e, 0x37, 0xd0, 0xc2, 0x6e, 0x79, 0x53, 0xf0, 0x00, 0xfd, 0x3c, 0xd9,
	0x06, 0x1e, 0x9d, 0xc2, 0xdd, 0x61, 0x5a, 0x1b, 0x33, 0x98, 0xd2, 0xd0, 0xfe, 0xff, 0xea, 0xcb,
	0xb7, 0x0f, 0xe6, 0xdf, 0xf6, 0x06, 0x3d, 0xdf, 0xba, 0xbe, 0x83, 0x34, 0x2d, 0x45, 0x9d, 0x7e,
	0xb1, 0xa3, 0x63, 0x34, 0xdb, 0x06, 0x4e, 0xd1, 0x2f, 0x53, 0x15, 0xe1, 0x8d, 0x89, 0xfa, 0xa7,
	0xa7, 0x61, 0x59, 0xb3, 0xa8, 0x51, 0xde, 0x3d, 0x9d, 0xf7, 0x8f, 0x6d, 0x4d, 0xe6, 0x95, 0x93,
	0x92, 0x9d, 0x72, 0x02, 0x1d, 0xa3, 0xb9, 0xfb, 0xae, 0xf2, 0xbe, 0xfb, 0xd5, 0xc4, 0x9f, 0xc7,
	0xed, 0xda, 0x87, 0x08, 0xbd, 0x10, 0xc0, 0x88, 0xee, 0x00, 0xff, 0x1e, 0x2b, 0x25, 0x64, 0x87,
	0x52, 0x2e, 0x80, 0xb5, 0x74, 0xc1, 0x4e, 0x08, 0xe7, 0xd6, 0x7f, 0xe3, 0xef, 0x56, 0x98, 0xc8,
	0x20, 0x97, 0x72, 0xa7, 0x7c, 0x32, 0x51, 0xc6, 0x73, 0x21, 0x9d, 0x80, 0xa7, 0xcd, 0x97, 0x08,
	0x77, 0x85, 0x1f, 0xc4, 0x40, 0x5c, 0xa7, 0x4d, 0x8e, 0x92, 0x00, 0x8a, 0xe3, 0xdf, 0xb9, 0xb6,
	0x8c, 0x12, 0x15, 0xe7, 0xbd, 0x42, 0x49, 0xcb, 0xad, 0x7d, 0x9e, 0x45, 0x7e, 0x0a, 0x72, 0x22,
	0x8c, 0xf6, 0x86, 0xbc, 0x47, 0x53, 0x5f, 0x2a, 0xc8, 0xe8, 0xd1, 0xe1, 0xde, 0xfe, 0xf3, 0x93,
	0x7d, 0xb7, 0xb2, 0xe5, 0xb4, 0x9b, 0xa6, 0x61, 0xba, 0x2b, 0xbe, 0x10, 0xc3, 0x24, 0xd0, 0xaf,
	0x8d, 0xbe, 0x91, 0x9c, 0x75, 0xee, 0x20, 0xde, 0x23, 0x54, 0xd9, 0x6e, 0x6f, 0xe3, 0x6d, 0xd4,
	0xf4, 0x40, 0xe5, 0x19, 0x83, 0x90, 0x5c, 0xc4, 0xc0, 0x88, 0x8a, 0x81, 0x64, 0x20, 0x79, 0x9e,
	0x05, 0x40, 0x42, 0x0e, 0x92, 0x30, 0xae, 0x08, 0xbc, 0x4d, 0xa4, 0x72, 0xf0, 0x3c, 0xaa, 0x7e,
	0x34, 0x8d, 0x85, 0xec, 0x31, 0xaa, 0x8f, 0x87, 0x41, 0x9e, 0xf0, 0x20, 0x2f, 0xee, 0x8d, 0x76,
	0xc7, 0xff, 0xce, 0x1e, 0x0d, 0x95, 0x89, 0x02, 0x1a, 0xf2, 0x40, 0xd2, 0x57, 0xe4, 0x16, 0x35,
	0xd1, 0x97, 0x18, 0x44, 0x54, 0xf4, 0x3e, 0x99, 0xb5, 0xc2, 0x5f, 0xdb, 0xf7, 0xe6, 0xf5, 0xdf,
	0xc5, 0x83, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed, 0x6b, 0x06, 0x05, 0xa8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendClient interface {
	// FetchMatch triggers execution of the specfied MatchFunction for each of the
	// specified MatchProfiles. Each MatchFunction execution returns a set of
	// proposals which are then evaluated to generate results. FetchMatch method
	// streams these results back to the caller.
	FetchMatches(ctx context.Context, in *FetchMatchesRequest, opts ...grpc.CallOption) (Backend_FetchMatchesClient, error)
	// AssignTickets sets the specified Assignment on the Tickets for the Ticket
	// IDs passed.
	AssignTickets(ctx context.Context, in *AssignTicketsRequest, opts ...grpc.CallOption) (*AssignTicketsResponse, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) FetchMatches(ctx context.Context, in *FetchMatchesRequest, opts ...grpc.CallOption) (Backend_FetchMatchesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Backend_serviceDesc.Streams[0], "/api.Backend/FetchMatches", opts...)
	if err != nil {
		return nil, err
	}
	x := &backendFetchMatchesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Backend_FetchMatchesClient interface {
	Recv() (*FetchMatchesResponse, error)
	grpc.ClientStream
}

type backendFetchMatchesClient struct {
	grpc.ClientStream
}

func (x *backendFetchMatchesClient) Recv() (*FetchMatchesResponse, error) {
	m := new(FetchMatchesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backendClient) AssignTickets(ctx context.Context, in *AssignTicketsRequest, opts ...grpc.CallOption) (*AssignTicketsResponse, error) {
	out := new(AssignTicketsResponse)
	err := c.cc.Invoke(ctx, "/api.Backend/AssignTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
type BackendServer interface {
	// FetchMatch triggers execution of the specfied MatchFunction for each of the
	// specified MatchProfiles. Each MatchFunction execution returns a set of
	// proposals which are then evaluated to generate results. FetchMatch method
	// streams these results back to the caller.
	FetchMatches(*FetchMatchesRequest, Backend_FetchMatchesServer) error
	// AssignTickets sets the specified Assignment on the Tickets for the Ticket
	// IDs passed.
	AssignTickets(context.Context, *AssignTicketsRequest) (*AssignTicketsResponse, error)
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_FetchMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchMatchesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackendServer).FetchMatches(m, &backendFetchMatchesServer{stream})
}

type Backend_FetchMatchesServer interface {
	Send(*FetchMatchesResponse) error
	grpc.ServerStream
}

type backendFetchMatchesServer struct {
	grpc.ServerStream
}

func (x *backendFetchMatchesServer) Send(m *FetchMatchesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Backend_AssignTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).AssignTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Backend/AssignTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).AssignTickets(ctx, req.(*AssignTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignTickets",
			Handler:    _Backend_AssignTickets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchMatches",
			Handler:       _Backend_FetchMatches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/backend.proto",
}
