// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.0
// source: api/evaluator.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A Matches proposed by the Match Function representing a candidate of the final results.
	Match         *Match `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_api_evaluator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_evaluator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_api_evaluator_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type EvaluateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A Match ID representing a shortlisted match returned by the evaluator as the final result.
	MatchId       string `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_api_evaluator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_evaluator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_api_evaluator_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

var File_api_evaluator_proto protoreflect.FileDescriptor

const file_api_evaluator_proto_rawDesc = "" +
	"\n" +
	"\x13api/evaluator.proto\x12\topenmatch\x1a\x12api/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"9\n" +
	"\x0fEvaluateRequest\x12&\n" +
	"\x05match\x18\x01 \x01(\v2\x10.openmatch.MatchR\x05match\"3\n" +
	"\x10EvaluateResponse\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\tR\amatchIdJ\x04\b\x01\x10\x022\x7f\n" +
	"\tEvaluator\x12r\n" +
	"\bEvaluate\x12\x1a.openmatch.EvaluateRequest\x1a\x1b.openmatch.EvaluateResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/evaluator/matches:evaluate(\x010\x01B\x8c\x03\x92A\xda\x02\x12\xb3\x01\n" +
	"\tEvaluator\"I\n" +
	"\n" +
	"Open Match\x12\x16https://open-match.dev\x1a#open-match-discuss@googlegroups.com*V\n" +
	"\x12Apache 2.0 License\x12@https://github.com/googleforgames/open-match/blob/master/LICENSE2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonR;\n" +
	"\x03404\x124\n" +
	"*Returned when the resource does not exist.\x12\x06\n" +
	"\x04\x9a\x02\x01\ar=\n" +
	"\x18Open Match Documentation\x12!https://open-match.dev/site/docs/Z open-match.dev/open-match/pkg/pb\xaa\x02\tOpenMatchb\x06proto3"

var (
	file_api_evaluator_proto_rawDescOnce sync.Once
	file_api_evaluator_proto_rawDescData []byte
)

func file_api_evaluator_proto_rawDescGZIP() []byte {
	file_api_evaluator_proto_rawDescOnce.Do(func() {
		file_api_evaluator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_evaluator_proto_rawDesc), len(file_api_evaluator_proto_rawDesc)))
	})
	return file_api_evaluator_proto_rawDescData
}

var file_api_evaluator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_evaluator_proto_goTypes = []any{
	(*EvaluateRequest)(nil),  // 0: openmatch.EvaluateRequest
	(*EvaluateResponse)(nil), // 1: openmatch.EvaluateResponse
	(*Match)(nil),            // 2: openmatch.Match
}
var file_api_evaluator_proto_depIdxs = []int32{
	2, // 0: openmatch.EvaluateRequest.match:type_name -> openmatch.Match
	0, // 1: openmatch.Evaluator.Evaluate:input_type -> openmatch.EvaluateRequest
	1, // 2: openmatch.Evaluator.Evaluate:output_type -> openmatch.EvaluateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_evaluator_proto_init() }
func file_api_evaluator_proto_init() {
	if File_api_evaluator_proto != nil {
		return
	}
	file_api_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_evaluator_proto_rawDesc), len(file_api_evaluator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_evaluator_proto_goTypes,
		DependencyIndexes: file_api_evaluator_proto_depIdxs,
		MessageInfos:      file_api_evaluator_proto_msgTypes,
	}.Build()
	File_api_evaluator_proto = out.File
	file_api_evaluator_proto_goTypes = nil
	file_api_evaluator_proto_depIdxs = nil
}
