proto_library(
    visibility = ["//visibility:public"],
    name = "backend_proto",
    srcs = ["backend.proto"],
    deps = [
        "//api:messages_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//protoc-gen-swagger/options:options_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//third_party/googleapis/google/api:annotations_proto",
    ],
)

proto_library(
    visibility = ["//visibility:public"],
    name = "evaluator_proto",
    srcs = ["evaluator.proto"],
    deps = [
        "//api:messages_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//protoc-gen-swagger/options:options_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//third_party/googleapis/google/api:annotations_proto",
    ],
)

proto_library(
    visibility = ["//visibility:public"],
    name = "frontend_proto",
    srcs = ["frontend.proto"],
    deps = [
        "//api:messages_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//protoc-gen-swagger/options:options_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//third_party/googleapis/google/api:annotations_proto",
    ],
)

proto_library(
    visibility = ["//visibility:public"],
    name = "matchfunction_proto",
    srcs = ["matchfunction.proto"],
    deps = [
        "//api:messages_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//protoc-gen-swagger/options:options_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//third_party/googleapis/google/api:annotations_proto",
    ],
)

proto_library(
    visibility = ["//visibility:public"],
    name = "messages_proto",
    srcs = ["messages.proto"],
    deps = [
        "@com_google_protobuf//:struct_proto",
    ],
)

proto_library(
    visibility = ["//visibility:public"],
    name = "mmlogic_proto",
    srcs = ["mmlogic.proto"],
    deps = [
        "//api:messages_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//protoc-gen-swagger/options:options_proto",
        "@com_github_grpc_ecosystem_grpc_gateway//third_party/googleapis/google/api:annotations_proto",
    ],
)